sudo: required
language: bash
services:
  - docker

before_install:
  - docker build -t yast-system-role-gnome-x11 .
script:
  - docker run -it -e TRAVIS=1 -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" system-role-gnome-x11 ./.travis.sh
